branches:
  only:
  - master
language: node_js
node_js:
  - "node"
before_install:
  - npm install
install:
  - echo 'secure key' >> $HOME/.ssh/known_hosts
script:
  - npm run build
deploy:
  provider: script
  script:
    - openssl aes-256-cbc -K $encrypted_1de3bcba7fca_key -iv $encrypted_1de3bcba7fca_iv -in deploy_key.enc -out ./deploy_key -d
    - eval "$(ssh-agent -s)"
    - chmod 600 ./deploy_key
    - echo -e "Host malte-bartels.de\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - ssh-add ./deploy_key
    - sh deploy.sh
  on:
    branch: master
